name: nsfp

target:
  _target_: src.models.NSFP
  filter_size: 128
  act_fn: relu
  layer_size: 8
  itr_num: 5000
  lr: 8e-3
  min_delta: 5e-5
  early_patience: 30 # default is 30, set 100 to get better results (zeroflow setting.)
  point_cloud_range: [-51.2, -51.2, -3, 51.2, 51.2, 3]
  
iter_only: True